version: '3.8'
services:
  backend:
    container_name: back
    environment:
      WEB_APP_URL: ${WEB_APP_URL}
      BOT_API_KEY: ${BOT_API_KEY}
    build:
      context: ./server
      dockerfile: ./backend/Dockerfile
    ports:
      - '3030:3030'
    volumes:
      - ./backend/stickers:/app/stickers
    restart: always
  frontend:
    container_name: frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_ABOUT_LINK: ${REACT_APP_ABOUT_LINK}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'
    restart: always